name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Copying files to VPS
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: /var/www/nextjs/riccardonuzzone.dev
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          rmRemote: true
      - run: echo "🍏 This job's status is ${{ job.status }}."