name: riccardonuzzone.dev CI/CD pipeline
on: [push]
jobs:
  riccardonuzzone-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Verify package.json exists before deploy
        run: ls -la
      - name: Copying files to VPS
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./
          remote: /var/www/nextjs/riccardonuzzone.dev
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          rmRemote: true
      - name: Reinstalling packages
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/nextjs/riccardonuzzone.dev
            ls -la .
            echo "$PWD"
            npm i
      - name: Running build
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/nextjs/riccardonuzzone.dev
            npm run build
      - name: Restarting server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          script: pm2 restart riccardonuzzone.dev
      - run: echo "🍏 This job's status is ${{ job.status }}."